version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: lol-flex-analyst-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: lol_flex_analyst
      MARIADB_USER: lol_user
      MARIADB_PASSWORD: lol_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
